config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :projects do
    resources :comments
  end

  resources :projects do
    resources :project_contributions, only: [:new, :create]
    resources :comments
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root 'welcome#index'

  get 'profile', to: 'users#show', as: :user
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  validates :project, presence: true
  validates_presence_of :text
end

app/models/project.rb
class Project < ActiveRecord::Base
  acts_as_taggable

  has_many :comments
  has_many :rewards
  belongs_to :owner, class_name: 'User'
  has_many :project_contributions
  accepts_nested_attributes_for :rewards, :allow_destroy => true

  validates :name, :owner, presence: true

  mount_uploader :photo, PhotoUploader

  private

  def self.ransackable_scopes(auth_object = nil)
    %i(tagged_with)
  end
end

app/models/project_contribution.rb
class ProjectContribution < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  validates :user, :project, presence: true
end

app/models/reward.rb
class Reward < ActiveRecord::Base
	belongs_to :project
	
	validates :price, :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_many :owned_projects, class_name: 'Project', foreign_key: :owner_id
  has_many :project_contributions
  has_many :comments

  validates_presence_of :email, :name

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  expose(:q) { Project.ransack(params[:q]) }


  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  expose(:comment, attributes: :comment_params)
  expose(:project)

  def edit
  end

  def create
    self.comment = Comment.new(comment_params)
    comment.user_id = current_user.id
    comment.project_id = project.id
    if comment.save
      project.comments << comment
      redirect_to project_url(project)
      flash[:success] = 'Comment was successfully created.'
    else
      redirect_to project_url(project)
      flsh[:danger] = 'Can\'t create comment. Enter text.'
    end
  end

  def destroy
    comment.destroy
    redirect_to project_url
    flash[:danger] = 'Comment was successfully destroyed.'
  end

  private
    def comment_params
      params.require(:comment).permit(:text)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/project_contributions_controller.rb
class ProjectContributionsController < ApplicationController
  expose(:project_contribution, attributes: :project_contribution_params)
  expose(:project)

  def create
    project_contribution.user = current_user
    project_contribution.project = project

    if project_contribution.save
      project.project_contributions << project_contribution
      redirect_to project, flash: { success: 'Thank you for contributing!' }
    else
      render 'new'
    end
  end

  private
  def project_contribution_params
    params.require(:project_contribution).permit(:amount, :comment, :user_id, :project_id)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :authenticate_owner!, only: [:edit, :update, :destroy]

  expose_decorated(:project, attributes: :project_params)
  expose_decorated(:projects) { q.result }
  expose(:comments) { project.comments }
  expose(:comment) { Comment.new }
  expose(:project_contribution) { ProjectContribution.new }
  expose(:rewards) { project.rewards }
  
  def new
    project.rewards.build
  end
  
  def create
    project.owner = current_user

    if project.save
      flash[:success] = 'Project was successfully created.'
      redirect_to project
    else
      render 'new'
    end
  end

  def update
    if project.save
      flash[:success] = 'Project was successfully updated.'
      redirect_to project
    else
      render 'edit'
    end
  end

  def destroy
    project.destroy
    flash[:success] = 'Project was successfully destroyed.'
    redirect_to root_path
  end

  private
  def authenticate_owner!
    unless current_user == project.owner
      redirect_to project_url(project), flash: { error: 'You are not allowed to do that.' }
    end
  end

  def project_params
    params.require(:project).permit(:name, :description, :tag_list, :photo, rewards_attributes: [:price, :description])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  expose(:user) { current_user }
  before_action :authenticate_user!

  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  expose_decorated(:latest_projects, decorator: ProjectDecorator) { Project.order("created_at DESC").limit(3) }
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.haml
= simple_form_for [project, comment] do |f|
  - if comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - comment.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label "Add comment"
    = f.text_area :text, class: 'form-control'

  = f.submit 'Save', class: 'btn btn-success'

app/views/comments/_list.html.haml
.newest-comments.row
  .col-md-12
    %h4 Newest comments:
    %table.table.table-striped
      %thead
        %tr
          %th #
          %th Text
      %tbody
        - project.comments.order("created_at DESC").each do |comment|
          %tr
            %td= comment.id
            %td= comment.text

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-inverse
  .container
    .navbar-header
      =link_to root_path do
        %span.navbar-brand NightWing
    .collapse.navbar-collapse.navbar-ex1-collapse#toggled
      %ul.nav.navbar-nav
        %li= link_to 'Discover', projects_path
      .col-sm-4
        .navbar-form
          = search_form_for q do |f|
            .input-group
              = f.search_field :name_or_description_cont, class: "form-control"
              .input-group-btn
                = f.submit "Search", class: "btn btn-default"
      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %li= link_to current_user.email, user_path
          %li= link_to 'Logout', destroy_user_session_path, method: :delete
        - else
          %li= link_to 'Sign up', new_user_registration_path
          %li= link_to 'Sign in', new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Nightwing
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/nav'
    .container
      - flash.each do |key, value|
        .alert{ class: "alert-#{key}"}
          = value
    .container
      .row
        .col-lg-12
          = yield

app/views/project_contributions/_form.html.haml
.form-horizontal
  = simple_form_for(project_contribution, url: project_project_contributions_path(project), html: { role: 'form' }) do |f|
    .form-inputs.inputs-modal
      = f.input :amount, class: 'form-control'
      = f.input :comment, class: 'form-control'
    .form-actions
      = f.submit "Contribute", class: 'btn btn-success'

app/views/project_contributions/_modal.html.haml
#myModal.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
        %h3#myModalLabel.modal-title
          Contribute to
          %b= project.name
      .modal-body
        = render 'project_contributions/form'

app/views/projects/_form.html.haml
.row
  .col-md-12
    = simple_form_for project do |f|
      .form-inputs
        = f.input :name
        = f.input :tag_list
        = f.input :description, class: 'form-control'
        .form-group
          - if project.photo?
            %label Current photo
            =image_tag project.photo.url(:thumb)
          - else
            %label Add photo
            = f.file_field :photo
            
        %h3 Rewards
        = f.simple_fields_for :rewards do |r|
          .duplicatable_nested_form
            = r.input :price
            = r.input :description
        = link_to 'Add Another Reward', '', :class => 'duplicate_nested_form', remote: true
      
      .form-actions
        = f.submit 'Save', class: 'btn btn-default btn-block'
        %br
        = link_to "Back", :back, class: 'btn btn-info'

app/views/projects/_supporters.html.haml
- if project.project_contributions.present?
  .new-project-contr.row
    .col-md-12
      .panel.panel-success
        .panel-heading
          %h3.panel-title Supporters
        .panel-body
          - project.project_contributions.each do |contribution|
            =link_to contribution.user do
              %li= contribution.user.name

app/views/projects/_tags.html.haml
- if project.tags.present?
  .new-project-tags.row
    .col-md-12
      .panel.panel-success
        .panel-heading
          %h3.panel-title Tags
        .panel-body
          = project.pretty_tag

app/views/projects/edit.html.haml
.container
  .row
    .col-md-12
      .page-header
        %h2.text-center
          Edit Project
      = render 'form'

app/views/projects/index.html.haml
- projects.each do |project|
  .row
    .col-lg-12
      .well
        .row
          .col-md-4.text-center
            - if project.photo?
              = image_tag project.photo.url(:thumb)
            - else
              %img{src: 'http://1.bp.blogspot.com/-PJyt12nd17s/T5ZEcR9p5fI/AAAAAAAAANc/0ORWu4BWGeY/s000/random_grey_variations.png', alt: project.name}

          .col-md-8
            %h2= link_to project.name, project
            = project.pretty_tag

app/views/projects/new.html.haml
.container
  .row
    .col-md-12
      .page-header
        %h2
          Create new project
      = render 'form'

app/views/projects/show.html.haml
.row
  .col-md-12
    .page-header
      %h2.text-center
        = project.name
        %p
          by
          = link_to project.owner do
            = project.owner.name
.row
  .col-md-8
    - unless project.photo.nil?
      = image_tag project.photo.url(:medium), alt: project.name
    - else
      %img{src: 'http://dummyimage.com/600x400/237d00/ffffff', alt: project.name}
    .project_description.froala-view
      = simple_format project.description
  .col-md-4
    .col-md-12.project_info
      %i.fa.fa-comment
        = project.comments.count
      comments
      %i.fa.fa-bullhorn
        = project.rewards.count
      rewards
    .project_info.supporters
      = render 'tags'
    .project_info.supporters
      = render 'supporters'

    .col-md-12.project_info
      - if current_user.present? and current_user == project.owner
        = link_to 'Edit Project', edit_project_path(project), class: 'btn btn-default btn-small'
        = link_to 'Delete', project_path(project), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-small'
      = link_to 'Back', :back, class: 'btn btn-default'
    
    .col-md-12
      %h3 Rewards
    .col-md-12
      - rewards.each do |reward|
        .panel.panel-default
          .panel-heading $ #{reward.price}
          .panel-body
            = reward.description
%br
%br
.new-project-module.row
  .col-md-12
    .panel.panel-success
      .panel-heading
        %h3.panel-title Create comment
      .panel-body
        = render 'comments/form'
%br
%h3 Comments:
= render 'comments/list', project: project

%button.btn.btn-success.btn-lg{"data-target": "#myModal", "data-toggle": "modal", type: "button"} Contribute

= render 'project_contributions/modal'

app/views/users/show.html.haml
.user.row
  .col-md-1
  .col-md-10
    %table.table.table-striped.wide-table
      %thead
        %tr
          %th #
          %th Name
          %th Email
          %th Edit
      %tbody
        %tr
          %td= user.id
          %td= user.name
          %td= user.email
          %td= link_to "Edit", edit_user_registration_path
  .col-md-1

.user-projects.row
  .col-md-1
  .col-md-10
    %h4 Projects created by this user:
    %table.table.table-striped.wide-table
      %thead
        %tr
          %th Name
      %tbody
        - user.owned_projects.each do |project|
          %tr
            %td= link_to project.name, project
  .col-md-1

app/views/welcome/_carousel.haml
.carousel.slide{ id: "slide-images", data: { ride: "carousel" }}
  %ol.carousel-indicators
    %li.active{ data: { target: "#slide-images", slide_to: "0" }}
    %li{ data: { target: "#slide-images", slide_to: "1" }}
    %li{ data: { target: "#slide-images", slide1_to: "2" }}

  .carousel-inner.text-center
    .item.active
      .fill{ style: "background-image: url(#{image_path 'pexels1.jpg'})"}
      .carousel-caption
        %h1 Raise funds and pursue your ideas
        = link_to "Start a campaing", new_project_path, class: 'btn btn-success'
    .item
      .fill{ style: "background-image: url(#{image_path 'pexels2.jpg'})"}
      .carousel-caption
        %h1 Back interesting projects
        = link_to "Discover projects", projects_path, class: 'btn btn-success'
    .item
      .fill{ style: "background-image: url(#{image_path 'pexels3.jpg'})"}
      .carousel-caption
        %h1 Be a part of the greatest community!
        = link_to "Sign up", new_user_registration_path, class: 'btn btn-success'

  %a.left.carousel-control{ href: "#slide-images", role: "button", data: { slide: "prev"}}
    %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
    %span.sr-only Previous

  %a.right.carousel-control{ href: "#slide-images", role: "button", data: { slide: "next" }}
    %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
    %span.sr-only Next

app/views/welcome/_projects.haml
- latest_projects.each_slice(3) do |slice|
  - slice.each do |project|
    .col-lg-4
      .thumbnail.text-center
        - if project.photo?
          = image_tag project.photo.url(:thumb)
        - else
          %img{src: 'http://1.bp.blogspot.com/-PJyt12nd17s/T5ZEcR9p5fI/AAAAAAAAANc/0ORWu4BWGeY/s000/random_grey_variations.png', alt: project.name}
        .caption
          %h2
            = link_to project.name, project
            = project.pretty_tag

app/views/welcome/index.haml
=render 'carousel'

.row.text-center
  .col-lg-12
    %h1 Welcome to Nightwing!
    %hr.divider

.row
  .col-lg-12.text-center
    %h3 Take a look at our latest projects...

.row
  .col-lg-12
    =render 'projects'